Sequencing Update for Portal Containers
hubmapconsortium/ingest-pipeline pull request #249
Opened 2021-03-11 17:05 UTC by ilan-gold

Forgot that @mruffalo was making the `hubmap_ui` directory so need to merge https://github.com/hubmapconsortium/portal-containers/pull/61 first and re-update.

2021-03-11 19:35 UTC, ilan-gold commented
Ready to go @jswelling! Hope this works!

2021-03-12 20:12 UTC, jswelling requested changes
I found one typo, at line 224 of salmon_rnaseq.py- see below.  Also, it looks like the update undoes a bunch of deletions of obsolete CWL pipelines that @mruffalo has been working throught.  Is that intended?

2021-03-12 20:12 UTC, jswelling commented on src/ingest-pipeline/airflow/dags/salmon_rnaseq.py
> +                "test_op": "t_convert_for_ui_2",
test_op should be "convert_for_ui_2", the task_id of the step.  t_convert_for_ui_2 is the name of the python variable pointing to the step.

2021-03-12 20:41 UTC, jswelling approved these changes
Thanks!

2021-03-12 20:45 UTC, merged