issue_602
hubmapconsortium/ingest-pipeline pull request #629
Opened 2022-07-13 15:29 UTC by sunset666

This PR removes a sudo command performed by move task on airflow DAGs, this isn't needed and can mislead when debugging.

2022-07-22 15:31 UTC, Daghis approved these changes

2022-07-28 18:35 UTC, jswelling requested changes
If this is the only reference to OUTPUT_GROUP_NAME in the config information, that parameter should probably be removed from the example config as well.

2022-10-13 17:40 UTC, jswelling approved these changes

2022-10-21 18:10 UTC, jpuerto-psc approved these changes

2022-10-21 18:12 UTC, merged