Welling/diagnostic from validation plugins
hubmapconsortium/ingest-pipeline pull request #688
Opened 2022-12-06 21:20 UTC by jswelling

This PR causes ingest-validation-test plugins of low 'cost' to be run against the parents of the failed dataset, to see if those parents would pass validation under current rules.  It includes:
* collection of data type and data path lists for the parent datasets
* code to find the path to the ingest-validation-tests plugins
* moving the always-passes and always-fails tests to a new subdirectory for deactivated plugins

2022-12-06 21:24 UTC, jswelling commented
Closes https://github.com/hubmapconsortium/ingest-pipeline/issues/681

2022-12-07 02:24 UTC, sunset666 requested changes

2022-12-07 05:24 UTC, jswelling commented on src/ingest-pipeline/misc/tools/airflow_startup_scripts/source_to_start_PROD_EM.sh
> +#queue=general_${instance},gpu000_q1_${instance}
done.

2022-12-10 02:30 UTC, sunset666 approved these changes

2022-12-13 15:16 UTC, merged